import { Food } from "../shared/schema";

// Initial food data
export const initialFoods: Omit<Food, "id" | "description">[] = [
  {
    name: "Spinach",
    category: "Leafy Green Vegetable",
    oxalateContent: 755,
    oxalateLevel: "high",
    servingSize: "100g (raw)",
    alternativeTip: "Kale, Lettuce",
  },
  {
    name: "Almonds",
    category: "Nuts",
    oxalateContent: 469,
    oxalateLevel: "high",
    servingSize: "100g",
    alternativeTip: "Macadamia, Walnuts",
  },
  {
    name: "Rhubarb",
    category: "Vegetable/Fruit",
    oxalateContent: 541,
    oxalateLevel: "high",
    servingSize: "100g",
    alternativeTip: "Apples, Berries",
  },
  {
    name: "Beets",
    category: "Root Vegetable",
    oxalateContent: 675,
    oxalateLevel: "high",
    servingSize: "100g",
    alternativeTip: "Carrots, Turnips",
  },
  {
    name: "Carrots",
    category: "Root Vegetable",
    oxalateContent: 45,
    oxalateLevel: "medium",
    servingSize: "100g (raw)",
    alternativeTip: "Peel to reduce oxalates",
  },
  {
    name: "Sweet Potato",
    category: "Root Vegetable",
    oxalateContent: 28,
    oxalateLevel: "medium",
    servingSize: "100g (cooked)",
    alternativeTip: "Boil before baking",
  },
  {
    name: "Peanuts",
    category: "Legume",
    oxalateContent: 34,
    oxalateLevel: "medium",
    servingSize: "100g",
    alternativeTip: "Macadamia nuts",
  },
  {
    name: "Cucumber",
    category: "Fruit Vegetable",
    oxalateContent: 2,
    oxalateLevel: "low",
    servingSize: "100g (raw)",
    alternativeTip: "Hydrating, cooling",
  },
  {
    name: "Cauliflower",
    category: "Cruciferous Vegetable",
    oxalateContent: 1,
    oxalateLevel: "low",
    servingSize: "100g (raw)",
    alternativeTip: "Rich in vitamin C",
  },
  {
    name: "White Rice",
    category: "Grain",
    oxalateContent: 4,
    oxalateLevel: "low",
    servingSize: "100g (cooked)",
    alternativeTip: "Easy to digest",
  },
  {
    name: "Watermelon",
    category: "Fruit",
    oxalateContent: 0.4,
    oxalateLevel: "low",
    servingSize: "100g",
    alternativeTip: "Hydrating, refreshing",
  },
  {
    name: "Apples",
    category: "Fruit",
    oxalateContent: 0.5,
    oxalateLevel: "low",
    servingSize: "100g",
    alternativeTip: "Rich in fiber",
  },
  {
    name: "Broccoli",
    category: "Cruciferous Vegetable",
    oxalateContent: 2,
    oxalateLevel: "low",
    servingSize: "100g (raw)",
    alternativeTip: "Steam for best nutrition",
  },
  {
    name: "Potatoes",
    category: "Root Vegetable",
    oxalateContent: 18,
    oxalateLevel: "medium",
    servingSize: "100g (cooked)",
    alternativeTip: "Boiling reduces oxalates",
  },
  {
    name: "Chocolate",
    category: "Confectionery",
    oxalateContent: 117,
    oxalateLevel: "high",
    servingSize: "100g",
    alternativeTip: "White chocolate has less",
  },
  {
    name: "Tea",
    category: "Beverage",
    oxalateContent: 55,
    oxalateLevel: "high",
    servingSize: "240ml (8oz)",
    alternativeTip: "Herbal teas are better",
  },
  {
    name: "Black Pepper",
    category: "Spice",
    oxalateContent: 35,
    oxalateLevel: "medium",
    servingSize: "5g (1tsp)",
    alternativeTip: "Use herbs instead",
  },
  {
    name: "Strawberries",
    category: "Fruit",
    oxalateContent: 2,
    oxalateLevel: "low",
    servingSize: "100g",
    alternativeTip: "Rich in vitamin C",
  },
  {
    name: "Chickpeas",
    category: "Legume",
    oxalateContent: 8,
    oxalateLevel: "low",
    servingSize: "100g (cooked)",
    alternativeTip: "Soak before cooking",
  },
  {
    name: "Cashews",
    category: "Nuts",
    oxalateContent: 260,
    oxalateLevel: "high",
    servingSize: "100g",
    alternativeTip: "Macadamia nuts",
  }
];
